name: Docker Build, Test and Push

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

env:
  REGISTRY: docker.io
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        run: |
          docker build -t $REPO_NAME:test .

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your actual test commands here
          docker run --rm $REPO_NAME:test echo "Tests passed"

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for commit count

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate version from commit count
        id: version
        run: |
          # Get total commit count for simple versioning
          COMMIT_COUNT=$(git rev-list --count HEAD)
          VERSION="1.0.$COMMIT_COUNT"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Verify push
        run: |
          echo "Successfully pushed:"
          echo "  - ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}"
          echo "  - ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest"